### ISSUE TITLE
Crash on server error

### ISSUE THREAD

**Issue by tochnonement** [danielga/gm_luaerror#37]
When any error occurs on the server side, the server crashes
![изображение](https://user-images.githubusercontent.com/48033052/113479987-b192e280-949a-11eb-998f-663de64f4225.png)
[MDMP File Download](https://github.com/danielga/gm_luaerror/files/6252630/srcds_crash.zip)
To watch web - https://dumps.metastruct.uk.to/analyze/34f26264bce2375373acb7a269422c491f08908d5e4d091f03a64a91f3123d13

**Comment by danielga** [comment]
What Garry's Mod branch (main or x86-64) and architecture (32 bits or 64 bits) are you using?

**Comment by tochnonement** [comment]
> 
> 
> What Garry's Mod branch (main or x86-64) and architecture (32 bits or 64 bits) are you using?

I use main branch and my server's architecture is 32 bits

**Comment by tochnonement** [comment]
This error doesn't exist before last Garry's Mod update

**Comment by danielga** [comment]
Should be fixed with [this release](https://github.com/danielga/gm_luaerror/releases/tag/1.5.5).

**Comment by tochnonement** [comment]
Still crashes

![изображение](https://user-images.githubusercontent.com/48033052/113491230-dbb6c580-94d7-11eb-8b8b-ebce217d0ad4.png)
[srcds_crash_2021_4_3T20_53_42C0.zip](https://github.com/danielga/gm_luaerror/files/6253366/srcds_crash_2021_4_3T20_53_42C0.zip)

**Comment by tochnonement** [comment]
I tried to call this error on server with previous Garry's Mod version, there everything is fine.
This error is caused by new version

**Comment by danielga** [comment]
I was having some trouble replicating with debug builds. I believe it should be fixed properly now. [Builds will show up here.](https://github.com/danielga/gm_luaerror/releases/tag/1.5.6)

**Comment by tochnonement** [comment]
Everything is fine now, thank you
